config/routes.rb
Rails.application.routes.draw do

  get '/signup', to: 'users#new'

  root 'static_pages#home'
  # get '/home', to: 'static_pages/home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello 
    render html: 'hello, world'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title='') 
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty? 
      base_title
    else 
      page_title + " | " + base_title 
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small>
    The <a href='http://www.railstutorial.org/'>Ruby on Rails Tutorial</a>
    By <a href='http://www.michaelhartl.com/'>Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', about_path%></li>
      <li><%=link_to 'Contact', contact_path%></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class='container'>
      <header class='navbar navbar-fixed-top navbar-inverse'>

        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class='nav navbar-nav navbar-right'>
            <li><%= link_to "home",   root_path %></li>
            <li><%= link_to "help",   help_path %></li>
            <li><%= link_to "signin", '#'%></li>
          </ul>
        </nav>
      <header>
    </div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
  <div>
    <%= render 'layouts/header'%>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
  <body>
    <h1>This is the about page</h1>
  </body>
</html>

app/views/static_pages/contact.html.erb
<%provide(:title, "Contact" )%>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
  <h1>Help</h1>
  <p>
    Get help at 
    <a href="http://www.railstutorial.org/help">Rails Tutorial Help
    </a>
  </p>

app/views/static_pages/home.html.erb
<div class='jumbotron center'>
  <h1>Welcome to the Sample App</h1>
  
  <h2>
    this is the homepage for
    <a href='http://www.railstutorial.org/'>Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  <%= link_to "Sign up now!", signup_path, class: 'btn btn-primary btn-lg'%>
</div>
  <%= link_to image_tag("rails.png", alt: 'Rails Logo'), 'http://rubyonrails.org/'%>

app/views/users/new.html.erb
<% provide(:title, "Sign Up" ) %>

<h1>SignUp!</h1>